STAGES = {
    "Uncertain": "Unc",
    "Uruk IV": "Uruk4",
    "Uruk III-Jemdet Nasr": "JN",
    "ED I-II": "ED1_2",
    "Fara": "Fara",
    "Presargonic": "PSarg",
    "Sargonic": "Sarg",
    "Ur III": "Ur3",
    "Old Assyrian": "OA",
    "Old Babylonian": "OB",
    "Middle Babylonian": "MB",
    "Middle Assyrian": "MA",
    "Hittite": "Hit",
    "Neo-Assyrian": "NA",
    "Neo-Babylonian": "NB",
    "Late Babylonian": "LB",
    "Persian": "Per",
    "Hellenistic": "Hel",
    "Parthian": "Par",
    "Proto-Elamite": "PElam",
    "Old Elamite": "OElam",
    "Middle Elamite": "MElam",
    "Neo-Elamite": "NElam",
    "Standard Babylonian": "SB",
}


PROVENANCES = {
    "Standard Text": "Std",
    "Assyria": "Assa",
    "Aššur": "Ašš",
    "Ḫuzirina": "Huz",
    "Kalḫu": "Kal",
    "Khorsabad": "Kho",
    "Nineveh": "Nin",
    "Tarbiṣu": "Tar",
    "Babylonia": "Baba",
    "Babylon": "Bab",
    "Borsippa": "Bor",
    "Cutha": "Cut",
    "Dilbat": "Dil",
    "Isin": "Isn",
    "Kiš": "Kiš",
    "Larsa": "Lar",
    "Meturan": "Met",
    "Nērebtum": "Nēr",
    "Nippur": "Nip",
    "Sippar": "Sip",
    "Šaduppûm": "Šad",
    "Ur": "Ur",
    "Uruk": "Urk",
    "Alalakh": "Ala",
    "Tell el-Amarna": "Ama",
    "Emar": "Emr",
    "Ḫattuša": "Hat",
    "Mari": "Mar",
    "Megiddo": "Meg",
    "Susa": "Sus",
    "Ugarit": "Uga",
    "Dūr-Katlimmu": "Dka",
    "Ḫarrān": "Har",
    "Imgur-Enlil": "Img",
    "Kār-Tukulti-Ninurta": "Ktn",
    "Šubat-Enlil": "Šub",
    "Guzana": "Guz",
    "Adab": "Adb",
    "Ešnunna": "Ešn",
    "Girsu": "Gir",
    "Lagaš": "Lag",
    "Nigin": "Nig",
    "Sippar-Amnānum": "Sipam",
    "Šuruppak": "Šur",
    "Ḫursagkalama": "Hur",
    "Tutub": "Ttb",
    "Umma": "Umm",
    "Zabalam": "Zab",
    "Bad-Tibira": "Btb",
    "Dūr-Kurigalzu": "Dku",
    "Eridu": "Eri",
    "Garšana": "Gar",
    "Irisagrig": "Irs",
    "Kisurra": "Ksr",
    "Kutalla": "Kut",
    "Marad": "Mrd",
    "Maškan-šāpir": "Maš",
    "Puzriš-Dagān": "Puz",
    "Larak": "Lrk",
    "Pī-Kasî": "Pik",
    "Malgium": "Mal",
    "Pašime": "Paš",
    "Tuttul": "Ttl",
    "Elam": "Elam",
    "Anšan": "Anš",
    "Dēr": "Der",
    "Dūr-Untaš": "Dun",
    "Ebla": "Ebl",
    "Kaneš": "Kan",
    "Karkemiš": "Kar",
    "Persepolis": "Per",
    "Terqa": "Ter",
    "Tepe Gotvand": "Tgo",
    "Qaṭnā": "Qaṭ",
    "Uncertain": "Unc",
}

PERIODS = {
    "None": "",
    "Uncertain": "Unc",
    "Uruk IV": "Uruk4",
    "Uruk III-Jemdet Nasr": "JN",
    "ED I-II": "ED1_2",
    "Fara": "Fara",
    "Presargonic": "PSarg",
    "Sargonic": "Sarg",
    "Ur III": "Ur3",
    "Old Assyrian": "OA",
    "Old Babylonian": "OB",
    "Middle Babylonian": "MB",
    "Middle Assyrian": "MA",
    "Hittite": "Hit",
    "Neo-Assyrian": "NA",
    "Neo-Babylonian": "NB",
    "Late Babylonian": "LB",
    "Persian": "Per",
    "Hellenistic": "Hel",
    "Parthian": "Par",
    "Proto-Elamite": "PElam",
    "Old Elamite": "OElam",
    "Middle Elamite": "MElam",
    "Neo-Elamite": "NElam",
}

TYPES = {
    "Library": "",
    "School": "Sch",
    "Varia": "Var",
    "Commentary": "Com",
    "Quotation": "Quo",
    "Excerpt": "Ex",
    "Parallel": "Par",
    "None": "",
}
